version: '3'

services:
  auth:
    image: 'node'
    volumes:
      - ./app:/app
    working_dir: /app
    command: 'yarn start'
    ports:
      - 8080:8080
  redis:
    image: 'redis'
    ports:
      - 6379:6379
