version: "3"

services:
  auth:
    image: "node"
    volumes:
      - ./app:/app
    working_dir: /app
    command: "bash -c 'yarn && yarn start'"
    ports:
      - 5050:8080
    networks:
      - backend
  redis:
    image: "redis"
    ports:
      - 6379:6379
    networks:
      - backend

networks: 
  backend: